language: php
dist: xenial

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

php:
  - 7.3

env:
  matrix:
    - SCENARIO=df
    - SCENARIO=dfs_one

services:
  - mysql

addons:
  chrome: stable
  apt:
    packages:
    # Dependencies for Chrome.
    - libappindicator1
    - fonts-liberation

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Update composer.
  - composer self-update
  - composer --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'df'@'localhost' IDENTIFIED BY 'df'; GRANT ALL ON drupal.* TO 'df'@'localhost';"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini

  # Build the DF code base.
  - composer require --dev acquia/lightning_dev:dev-8.x-1.x --no-update
  - COMPOSER_MEMORY_LIMIT=-1 composer install

  # Install DF.
  - lightning install 'mysql\://df:df@127.0.0.1/drupal' $SCENARIO 'http://127.0.0.1:8080' --no-dev

  # Generate the Behat config.
  - lightning configure:behat 'http://127.0.0.1:8080'
  - cd docroot

before_script:
  - drush runserver --default-server=builtin --quiet 8080 &
  - chromedriver --port=4444 &

script:
  - if [[ "$SCENARIO" != df ]]; then behat --config .behat.yml --stop-on-failure --tags=$SCENARIO; fi

matrix:
  fast_finish: true
